from django.contrib import admin
from xchem_db.models import (
BadAtoms,
FragalysisLigand,
MiscFiles,
PanddaSite,
ReviewResponses,
Compounds,
FragalysisTarget,
PanddaAnalysis,
PanddaStatisticalMap,
Crystal,
Lab,
PanddaEvent,
Proposals,
SoakdbFiles,
DataProcessing,
Ligand,
PanddaEventStats,
Reference,
Target,
Dimple,
MetaData,
PanddaRun,
Refinement,
SiteMapping,
ProteinSite
)

admin.site.register(BadAtoms)
admin.site.register(FragalysisLigand)
admin.site.register(MiscFiles)
admin.site.register(PanddaSite)
admin.site.register(ReviewResponses)
admin.site.register(Compounds)
admin.site.register(FragalysisTarget)
admin.site.register(PanddaAnalysis)
admin.site.register(PanddaStatisticalMap)
admin.site.register(SiteMapping)
admin.site.register(ProteinSite)
admin.site.register(Crystal)
admin.site.register(Lab)
admin.site.register(PanddaEvent)
admin.site.register(Proposals)
admin.site.register(SoakdbFiles)
admin.site.register(DataProcessing)
admin.site.register(Ligand)
admin.site.register(PanddaEventStats)
admin.site.register(Reference)
admin.site.register(Target)
admin.site.register(Dimple)
admin.site.register(MetaData)
admin.site.register(PanddaRun)
admin.site.register(Refinement)
