services:
  db:
    image: mariadb
    restart: always
    container_name: db
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci', '--init-file=/data/application/init.sql']
    volumes:
      - .init.sql:/data/application/init.sql
    environment:
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker-root"
      MYSQL_ROOT_HOST: "%"

  web:
    depends_on:
      - db
    build: .
    volumes:
      - .:/xcdb
    command: >
      /bin/bash -c "python3.6 manage.py makemigrations &&
      python3.6 manage.py migrate &&
      python3.6 manage.py makemigrations xchem_db &&
      python3.6 manage.py migrate xchem_db &&
      python3.6 manage.py graph_models -a -o schema.png &&
      python3.6 run_sql_gen.py &&
      python3.6 compile_init.py &&
      python3.6 manage.py runserver 0.0.0.0:8000"
    container_name: xcdb
    restart: always
    ports: 
      - "8000:8000"