services:
  db:
    image: mariadb
    restart: always
    container_name: db
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      MYSQL_ROOT_PASSWORD: "docker-root"

  web:
    build: .
    command: /bin/bash -c "python3.6 manage.py makemigrations && python3.6 manage.py migrate && python3.6 manage.py makemigrations xchem_db && python3.6 manage.py migrate xchem_db && python3.6 manage.py runserver 0.0.0.0:8000"
    container_name: xcdb
    restart: always
    volumes:
      - .:/xcdb
    ports: 
      - "8000:8000"
    depends_on:
      - db
