# Generated by Django 3.1.7 on 2021-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchem_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresponses',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
