# Generated by Django 3.1.7 on 2021-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xchem_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badatoms',
            name='review',
        ),
        migrations.AddField(
            model_name='target',
            name='pl_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='pl_additional_headers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='pl_covalent_attachments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='pl_monomeric',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='pl_reduce_reference_frame',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='pl_reference',
            field=models.FileField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='badatoms',
            name='atomid',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='compound',
        ),
        migrations.AddField(
            model_name='crystal',
            name='compound',
            field=models.ManyToManyField(to='xchem_db.Compounds'),
        ),
        migrations.DeleteModel(
            name='PipelineParams',
        ),
    ]
