# Generated by Django 3.1.7 on 2021-05-14 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xchem_db', '0002_auto_20210325_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresponses2',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SWStatuschange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activation', models.BooleanField(default=False)),
                ('source_well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='xchem_db.sourcewell')),
            ],
        ),
        migrations.CreateModel(
            name='PlateOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened', to='xchem_db.libraryplate')),
            ],
        ),
    ]
