# Generated by Django 3.1.7 on 2021-05-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xchem_db', '0003_auto_20210514_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='metadata',
            table='MetaData',
        ),
    ]
